version: "3.7"

services:
  postgres:
    image: romanchechyotkin/datachain-postgres:latest
    container_name: "postgres"
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5432"
      POSTGRES_DB: "datachain"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - microservices-network
  server:
    image: romanchechyotkin/datachain-go:latest
    volumes:
      - ./static:/app/static
    container_name: server
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "datachain"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5432"
    depends_on:
      - postgres
    networks:
      - microservices-network
    ports:
      - "8000:8000"

  frontend:
    image: romanchechyotkin/datachain-react:latest
    environment:
      NODE_ENV: "production"
      REACT_APP_BACKEND: "http://server:8000"
      REACT_APP_MINIO: "http://server:8000/static/"
    depends_on:
      - server
    networks:
      - microservices-network
    ports:
      - "3000:3000"

volumes:
  data:
  static:
    driver: local

networks:
  microservices-network:
    driver: bridge